languageCode = "en-us"
title = "Hylda example"
theme = "hylda"

paginate = 3

baseURL = "http://localhost:1313"

pygmentsCodeFences = true
pygmentsUseClasses = true

[permaLinks]
  posts = "/:year/:month/:day/:slug/"

[author]
  name = "Boris Bera"

[params.social]
  twitter = "dotboris"
  github = "dotboris"
  linkedin = "boris-bera-40673186"
  instagram = "boris.bera"
