languageCode = "en-us"
title = "Hylda example"
theme = "hylda"

paginate = 3

baseURL = "https://hylda-theme.netlify.com"

pygmentsCodeFences = true
pygmentsUseClasses = true

googleAnalytics = "UA-52565545-2"

[params]
  googleSiteVerificationCode = "IbLskKQDHp1Nausit9EgvP2ajuGUabwB6yGIpsYzjsU"

[permaLinks]
  posts = "/:year/:month/:day/:slug/"

[author]
  name = "Hylda theme"

[params.social]
  github = "dotboris/hylda"
