languageCode = "en-us"
title = "Hylda example"
theme = "hylda"

paginate = 3

baseURL = "http://localhost:1313"

pygmentsCodeFences = true
pygmentsUseClasses = true

[permaLinks]
  posts = "/:year/:month/:day/:slug/"

[author]
  name = "Hylda theme"

[params.social]
  github = "dotboris/hylda"
