languageCode = "en-us"
title = "Hylda example"
theme = "hylda"

paginate = 3

baseURL = "https://hylda-theme.netlify.com"

pygmentsCodeFences = true
pygmentsUseClasses = true

[permaLinks]
  posts = "/:year/:month/:day/:slug/"

[author]
  name = "Hylda theme"

[params]
  picture = "butts.jpg"

[params.social]
  github = "dotboris/hylda"
