name = "Hylda"
license = "MIT"
licenselink = "https://github.com/dotboris/hylda/blob/master/LICENSE.md"
description = ""
tags = []
features = []
min_version = "0.20"

[author]
  name = "Boris Bera"
  homepage = "https://dotboris.github.io"
  repo = "https://github.com/dotboris/hylda"
